version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    working_directory: ~/SE-Coursework/src
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install