version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    working_directory: SE-Coursework/src
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
