version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    working_directory: C:\Users\vinub\OneDrive - University of Roehampton\Software Engineering\src
    docker:
      - image: cimg/node:lts
    steps:
      - checkout:
        path: C:\Users\vinub\OneDrive - University of Roehampton\Software Engineering
      - run: npm install